[project]
name = "frontend"
version = "0.1.0"
description = "Streamlit frontend for eClipseBord - Azure Python Fullstack Lab"
readme = "README.md"
authors = [
    { name = "Aira Franco", email = "adelosofranco@gmail.com" }
]
requires-python = ">=3.13"
dependencies = ["streamlit", "httpx"]

[project.scripts]
frontend = "frontend:main"

[build-system]
requires = ["uv_build>=0.8.17,<0.9.0"]
build-backend = "uv_build"
